### PR TITLE
*: fix two issues

### LINKED ISSUE #277: workerInfo map occures data race
log:
```
65975 fatal error: concurrent map read and map write
 65976 
65977 goroutine 537429 [running]: 65978 runtime.throw({0x4501400?, 0x2e?})
65979         /root/go/src/runtime/panic.go:992 +0x71 fp=0xc01f321c50 sp=0xc01f321c20 pc=0x15b7771 
65980 runtime.mapaccess2_faststr(0x26e?, 0x53891d2?, {0xc00f1360c0, 0x24}) 
65981         /root/go/src/runtime/map_faststr.go:117 +0x3d4 fp=0xc01f321cb8 sp=0xc01f321c50 pc=0x15922d4 
65982 github.com/hanfei1991/microcosm/lib.(*workerManagerImpl).GetWorkerHandle(0xc00f5ea460, {0xc00f1360c0, 0x24}) 
65983         /root/microcosm/lib/worker_manager.go:493 +0x45 fp=0xc01f321d20 sp=0xc01f321cb8 pc=0x3841205
65984 github.com/hanfei1991/microcosm/lib.(*DefaultBaseMaster).CreateWorker.func1() 
65985         /root/microcosm/lib/master.go:636 +0xb31 fp=0xc01f321fe0 sp=0xc01f321d20 pc=0x3836bb1
65986 runtime.goexit() 65987         /root/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc01f321fe8 sp=0xc01f321fe0 pc=0x15ebc41 65988 created by github.com/hanfei1991/microcosm/lib.(*DefaultBaseMaster).CreateWorker
65989         /root/microcosm/lib/master.go:559 +0x576
```

When creating worker, get worker handler is not thread-safe

### PR DESCRIPTION
**Pull request by liuzix**
close #277 #278

### CODE REVIEW

File: lib/worker_manager.go [hunk 1]
```diff
@@ -490,6 +490,9 @@ func (m *workerManagerImpl) MessageSender() p2p.MessageSender {
 }
 
 func (m *workerManagerImpl) GetWorkerHandle(id WorkerID) WorkerHandle {
+	m.mu.Lock()
```
Comment (amyangfei) [inline lib/worker_manager.go:493]: `GetWorkers` also locks `m.mu` and calls `GetWorkerHandle`

File: lib/worker.go [hunk 2]
```diff
@@ -402,7 +402,16 @@ func (w *DefaultBaseWorker) runWatchDog(ctx context.Context) error {
 	}
 }
 
-func (w *DefaultBaseWorker) initMessageHandlers(ctx context.Context) error {
+func (w *DefaultBaseWorker) initMessageHandlers(ctx context.Context) (retErr error) {
+	defer func() {
+		if retErr != nil {
+			if err := w.messageHandlerManager.Clean(context.Background()); err != nil {
```
Comment (amyangfei) [inline lib/worker.go:408]: Can we use `ctx` here

Comment (liuzix) [reply lib/worker.go:408]: It could be possible that the `ctx` has been canceled.

**Review by amyangfei — APPROVED** [review]

**Review by nongfushanquan — APPROVED** [review]
